version: 2
jobs:
  asan:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh cmake.asan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  tsan:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh cmake.tsan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  clang_tidy:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/install_clang.sh
      - run: ./ci/do_ci.sh cmake.clang-tidy
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  build_with_no_grpc:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/install_protobuf.sh
      - run: ./ci/do_ci.sh cmake.no_grpc
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  build_plugin:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh plugin
      - store_artifacts:
          path: /liblightstep_tracer_plugin.so
          destination: liblightstep_tracer_plugin.so
  build_bazel:
    docker:
      - image: ubuntu:18.04
    resource_class: large
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.build
  release:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get -qq update; apt-get -y install git ssh
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh release

  coverage:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh coverage
      - store_artifacts:
          path: /coverage
          desination: coverage

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - asan
      - tsan
      - clang_tidy
      - build_with_no_grpc
      - build_plugin
      - build_bazel
      - coverage
