version: 2
jobs:
  asan:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh cmake.asan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  tsan:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh cmake.tsan
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  build_with_no_grpc:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/install_protobuf.sh
      - run: ./ci/do_ci.sh cmake.no_grpc
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log
  build_bazel:
    docker:
      - image: ubuntu:17.10
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.build

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - asan
      - tsan
      - build_with_no_grpc
      - build_bazel
