version: 2
jobs:
  cmake_no_grpc:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/install_protobuf.sh
      - run: ./ci/do_ci.sh cmake.minimal
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log

  cmake_with_grpc:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_grpc.sh
      - run: ./ci/install_libevent.sh
      - run: ./ci/install_cares.sh
      - run: ./ci/install_opentracing.sh
      - run: ./ci/do_ci.sh cmake.full
      - store_artifacts:
          path: /build/Testing/Temporary/LastTest.log
          destination: Test.log

  test:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.test

  asan:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_clang.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.asan

  tsan:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_clang.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.tsan

  release:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get -qq update; apt-get -y install git ssh
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh release

  benchmark:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.benchmark
      - store_artifacts:
          path: /benchmark
          desination: benchmark

  clang_tidy:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_clang.sh
      - run: ./ci/install_bazel.sh
      - run: 
          command: ./ci/do_ci.sh clang_tidy
          no_output_timeout: 1800
      - store_artifacts:
          path: /clang-tidy-result.txt
          destination: /clang-tidy-result.txt
      - store_artifacts:
          path: /clang-tidy-errors.txt
          destination: /clang-tidy-errors.txt

  build_plugin:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh plugin
      - store_artifacts:
          path: /liblightstep_tracer_plugin.so
          destination: liblightstep_tracer_plugin.so

  build_python_wheel:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/do_ci.sh python.wheel
      - run: cd /
      - run: tar zxf wheel.tgz
      - store_artifacts:
          path: /wheel
          destination: wheel
      - persist_to_workspace:
          root: /wheel
          paths:
            - "*"

  coverage:
    resource_class: xlarge
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: ./ci/setup_build_environment.sh
      - run: ./ci/install_bazel.sh
      - run: ./ci/do_ci.sh bazel.coverage
      - store_artifacts:
          path: /coverage
          desination: coverage

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - cmake_no_grpc
      - cmake_with_grpc
      - test
      - asan
      - tsan
      - benchmark
      - coverage
      - build_plugin
      - build_python_wheel
      - clang_tidy
